plugins {
    id 'java'
    id 'io.spring.dependency-management' version '1.1.7'
    id "com.github.spotbugs" version "6.0.5"
}

group = 'de.hhu.thesis_jensclicker.utility'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.5.10"
    }
}

tasks.withType(JavaCompile) {
    options.compilerArgs << "-parameters"
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation "org.commonmark:commonmark:0.27.0"

    compileOnly 'com.github.spotbugs:spotbugs-annotations:4.8.3'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

spotbugs {
    effort = com.github.spotbugs.snom.Effort.MAX
}
spotbugsMain {
    reports {
        xml.enabled = false
        html.enabled = true
    }
}

test {
    useJUnitPlatform()
}